import { useMemo, useState } from "react";
import data from "./data.json";

type Column = { key: string; label: string };
type Row = {
  name: string;
  source: string;
  summary: string;
  values: Record<string, string>;
};
type Data = {
  title: string;
  topic: string;
  generated_at: string;
  columns: Column[];
  rows: Row[];
};

const typed = data as Data;

export default function App() {
  const [query, setQuery] = useState("");
  const [activeFilters, setActiveFilters] = useState<Record<string, string | null>>({});

  const uniqueValues = useMemo(() => {
    const map: Record<string, Set<string>> = {};
    typed.columns.forEach((c) => (map[c.key] = new Set()));
    typed.rows.forEach((r) =>
      typed.columns.forEach((c) => {
        const v = r.values[c.key];
        if (v) map[c.key].add(v);
      }),
    );
    return map;
  }, []);

  const filtered = typed.rows.filter((r) => {
    const q = query.trim().toLowerCase();
    const matchesQuery =
      !q ||
      r.name.toLowerCase().includes(q) ||
      r.summary.toLowerCase().includes(q) ||
      Object.values(r.values).some((v) => v.toLowerCase().includes(q));
    const matchesFilters = Object.entries(activeFilters).every(
      ([k, v]) => !v || r.values[k] === v,
    );
    return matchesQuery && matchesFilters;
  });

  return (
    <div className="wrap">
      <header>
        <h1>{typed.title}</h1>
        <div className="sub">
          {typed.rows.length} items · generated {typed.generated_at}
        </div>
      </header>

      <div className="controls">
        <input
          type="search"
          placeholder="Filter by name, summary, or value…"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
        {typed.columns.map((col) => (
          <div key={col.key} style={{ display: "flex", gap: ".35rem", flexWrap: "wrap" }}>
            <span style={{ color: "var(--muted)", fontSize: ".82rem", alignSelf: "center" }}>
              {col.label}:
            </span>
            {[...uniqueValues[col.key]].sort().map((v) => {
              const active = activeFilters[col.key] === v;
              return (
                <button
                  key={v}
                  className={`filter-chip ${active ? "active" : ""}`}
                  onClick={() =>
                    setActiveFilters((f) => ({ ...f, [col.key]: active ? null : v }))
                  }
                >
                  {v}
                </button>
              );
            })}
          </div>
        ))}
        <span className="count">
          {filtered.length} / {typed.rows.length}
        </span>
      </div>

      {filtered.length === 0 ? (
        <div className="empty">No items match your filters.</div>
      ) : (
        <div className="grid">
          {filtered.map((r) => (
            <article key={r.name} className="card">
              <h2>
                <span>{r.name}</span>
                <a className="src" href={`../../../${r.source}`} title={r.source}>
                  source
                </a>
              </h2>
              <div className="summary">{r.summary}</div>
              <div className="values">
                {typed.columns.map((c) => (
                  <span key={c.key} className="pill">
                    <b>{c.label}</b>
                    {r.values[c.key] ?? "—"}
                  </span>
                ))}
              </div>
            </article>
          ))}
        </div>
      )}

      <footer>
        Generated by <code>/generate app</code> · comparison-explorer template
      </footer>
    </div>
  );
}
