import { useMemo, useState } from "react";
import data from "./data.json";

type Event = {
  date: string;
  title: string;
  source: string;
  summary: string;
  tags?: string[];
};
type Data = {
  title: string;
  topic: string;
  generated_at: string;
  events: Event[];
};

const typed = data as Data;

export default function App() {
  const [query, setQuery] = useState("");
  const [activeTag, setActiveTag] = useState<string | null>(null);
  const [sortDir, setSortDir] = useState<"asc" | "desc">("asc");

  const allTags = useMemo(() => {
    const s = new Set<string>();
    typed.events.forEach((e) => (e.tags ?? []).forEach((t) => s.add(t)));
    return [...s].sort();
  }, []);

  const sorted = useMemo(() => {
    const copy = [...typed.events];
    copy.sort((a, b) => (sortDir === "asc" ? a.date.localeCompare(b.date) : b.date.localeCompare(a.date)));
    return copy;
  }, [sortDir]);

  const filtered = sorted.filter((e) => {
    const q = query.trim().toLowerCase();
    const matchesQuery =
      !q ||
      e.title.toLowerCase().includes(q) ||
      e.summary.toLowerCase().includes(q) ||
      e.date.toLowerCase().includes(q);
    const matchesTag = !activeTag || (e.tags ?? []).includes(activeTag);
    return matchesQuery && matchesTag;
  });

  return (
    <div className="wrap">
      <header>
        <h1>{typed.title}</h1>
        <div className="sub">
          {typed.events.length} events · generated {typed.generated_at}
        </div>
      </header>

      <div className="controls">
        <input
          type="search"
          placeholder="Filter by title, summary, or date…"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
        <button
          className="tag-chip"
          onClick={() => setSortDir((d) => (d === "asc" ? "desc" : "asc"))}
          title="Toggle chronological order"
        >
          Sort: {sortDir === "asc" ? "oldest → newest" : "newest → oldest"}
        </button>
        {allTags.map((t) => {
          const active = activeTag === t;
          return (
            <button
              key={t}
              className={`tag-chip ${active ? "active" : ""}`}
              onClick={() => setActiveTag(active ? null : t)}
            >
              #{t}
            </button>
          );
        })}
        <span className="count">
          {filtered.length} / {typed.events.length}
        </span>
      </div>

      {filtered.length === 0 ? (
        <div className="empty">No events match.</div>
      ) : (
        <div className="tl">
          {filtered.map((e, i) => (
            <article key={`${e.date}-${i}`} className="tl-event">
              <div className="date">{e.date}</div>
              <h2>{e.title}</h2>
              <div className="summary">{e.summary}</div>
              <div className="meta">
                {(e.tags ?? []).map((t) => (
                  <span key={t} className="tag">#{t}</span>
                ))}
                <a className="src" href={`../../../${e.source}`}>source</a>
              </div>
            </article>
          ))}
        </div>
      )}

      <footer>
        Generated by <code>/generate app</code> · timeline template
      </footer>
    </div>
  );
}
